server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: /api
    application-display-name: blog-search-api

spring:
  application:
    name: blog-search-api

feign:
  url:
    prefix: "https://dapi.kakao.com"
  api:
    key:
      kakao: "a6e103182d0df70ff2689ba5d4b67ee3"
  client:
    config:
      kakaoFeignClient:
        connectTimeout: 1000
        readTimeout: 1000
        loggerLevel: HEADERS

